_DATA		SEGMENT DWORD PUBLIC 'DATA'
EXTRN		_OemHlpIDC:WORD
_DATA		ENDS

CONST		SEGMENT DWORD PUBLIC 'CONST'
CONST		ENDS

_BSS		SEGMENT DWORD PUBLIC 'BSS'
_BSS		ENDS

DGROUP		GROUP	CONST, _BSS, _DATA

		.386p
FCode		SEGMENT

		ASSUME	CS:FCode,DS:DGROUP

; USHORT FAR _fastcall CallOEMHlp (PRPH pRPH);

		public	@CallOEMHlp
@CallOEMHlp	PROC	FAR

		PUSH	BP
		MOV	BP, SP
		PUSH	SI
		PUSH	DI

		LES	BX, DWORD PTR [BP+6]
		TEST	WORD PTR [_OemHlpIDC.Entry], -1
		JNZ	DoOEMHlp

		MOV	AX, 8100h
		MOV	WORD PTR ES:[BX+3], AX
		JMP	SHORT CallOEMHlpEnd
DoOEMHlp:
		PUSH	[_OemHlpIDC.Entry]
		PUSH	DS
		MOV	DS, [_OemHlpIDC.DSeg]
		CALL	DWORD PTR [BP-8]
		POP	DS
		ADD	SP, 4
		MOV	AX, WORD PTR ES:[BX+3]
CallOEMHlpEnd:
		AND	AX, 8000h
		POP	DI
		POP	SI
		LEAVE
		RET	4

@CallOEMHlp	ENDP

FCode		ENDS

		END
